In [34]:
import pandas as pd
import sklearn
import numpy as np
from sklearn import *


In [35]:
train_data = pd.read_csv("train.csv")
sample_data = pd.read_csv("sample.csv")

In [39]:
lambdas = [0.1, 1, 10, 100, 200]
rmse = np.zeros(5)

for i in [0,1,2,3,4]:
    y = np.array(train_data.loc[:, 'y'])
    x = np.array(train_data.loc[:, 'x1':'x13'])

    kf = sklearn.model_selection.KFold(n_splits=10, shuffle=False)
    
    for train_index, test_index in kf.split(x):  
        ridge_model = linear_model.Ridge(alpha = lambdas[i])
        ridge_model.fit(x[train_index], y[train_index])
        ridge_predict = ridge_model.predict(x[test_index]) 
        true_y = y[test_index]
        # rmse[i] = np.sqrt(sum((true_y-ridge_predict)**2) / len(true_y))
        sklearn.metrics.mean_squared_error(true_y, ridge_predict)
    

In [42]:
pd.DataFrame(rmse).to_csv("outout.csv", header=None, index=None)

In [43]:
true_y

array([35.4, 24. , 13.4, 26.2,  7.2, 13.1, 24.5, 37.2, 25. , 24.1, 16.6,
       32.9, 36.2, 11. ,  7.2])

In [44]:
ridge_predict

array([31.53348051, 25.70991269, 12.46599609, 25.11683889,  6.19122924,
       15.18703823, 19.65470201, 31.5158503 , 28.15305316, 22.77177803,
       18.85231529, 28.40566362, 28.54085302, 13.40204063,  8.80977803])

In [45]:
true_y-ridge_predict

array([ 3.86651949, -1.70991269,  0.93400391,  1.08316111,  1.00877076,
       -2.08703823,  4.84529799,  5.6841497 , -3.15305316,  1.32822197,
       -2.25231529,  4.49433638,  7.65914698, -2.40204063, -1.60977803])

In [46]:
(true_y-ridge_predict)**2

array([14.94997296,  2.92380142,  0.87236331,  1.17323799,  1.01761844,
        4.35572857, 23.47691266, 32.30955786,  9.94174421,  1.7641736 ,
        5.07292419, 20.19905947, 58.66253248,  5.76979921,  2.59138531])

In [47]:
sum((true_y-ridge_predict)**2)

185.08081166305828